version : '3'
services :
  test :
    ports:
      - "3000:3000"
    container_name: tpnode
    build: .
    depends_on:
      - mongo
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root